Name :- Patel Viraj
PRN No :- 31

Name :- Vikramaditya Singh
PRN No :- 51

-----Q1-----

Q1. Create a DataFrame containing student information like Name, Age, Department, %Marks
a.	Display column names of the DF
b.	Show min/max and average marks
c.	Get unique values and student count for each Department

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_frame = {
'Name' : ['Vikram','Viraj','Sai Harshith','Priyanshu','Aashi','Aaditya','Abhishek','Nitin'],
'Age' :[24,21,21,23,22,23,24,21],
'Department' :['CS','IT','IT','CS','E&TC','CHEM','COMP','E&TC'],
'Marks':[90,93,87,70,49,75,69,73]
}
df = pd.DataFrame(data_frame)
df

           Name  Age Department  Marks
0        Vikram   24         CS     90
1         Viraj   21         IT     93
2  Sai Harshith   21         IT     87
3     Priyanshu   23         CS     70
4         Aashi   22       E&TC     49
5       Aaditya   23       CHEM     75
6      Abhishek   24       COMP     69
7         Nitin   21       E&TC     73

a. Display column names of the DF

In [3]:
print('Columns :- ',df.columns)

Columns :-  Index(['Name', 'Age', 'Department', 'Marks'], dtype='str')

b. Show min/max and average marks

In [4]:
print('Min Marks :- ',np.min(df['Marks']))

Min Marks :-  49

In [5]:
print('Max Marks :- ',np.max(df['Marks']))

Max Marks :-  93

In [6]:
print('Avg Marks :- ',np.average(df['Marks']))

Avg Marks :-  75.75

c. Get unique values and student count for each Department

In [7]:
df['Department'].unique()

<StringArray>
['CS', 'IT', 'E&TC', 'CHEM', 'COMP']
Length: 5, dtype: str

In [8]:
df['Department'].value_counts()

Department
CS      2
IT      2
E&TC    2
CHEM    1
COMP    1
Name: count, dtype: int64

-----Q2-----

Q2. Read csv file solar.csv
a.	Display all the plants with capacity > 500 MW
b.	Display plant details for New York plant
c.	For all the plants display Average MW Per Plant and Generation (GWh)
d.	Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)
e.	List top 5 plants for their Generation
f.	Display all plant details for states – California, Nevada, Arizona and Texas
g.	Group the plants by region, find – min/max capacity plant for each group
h.	Add following information to the existing details for the plants
	North Carolina	148	669	4.5	1162	North

In [9]:
df = pd.read_csv('solar.csv')
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

a. Display all the plants with capacity > 500 MW

In [10]:
filt = df['Installed Capacity (MW)'] > 500
df[filt]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South

b. Display plant details for New York plant

In [11]:
df[df['State'] == 'New York']

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East

 c. For all the plants display Average MW Per Plant and Generation (GWh)

In [12]:
df[['Average MW Per Plant','Generation (GWh)']]

   Average MW Per Plant  Generation (GWh)
0                  15.3             10826
1                  22.5              2550
2                  21.6               557
3                   7.9               590
4                   5.9               235
5                  15.6               354
6                   4.1                84
7                  12.3               453

 d. Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)

In [13]:
print('---By Generation (GWh) In Ascending---')
df.sort_values(by='Generation (GWh)')

---By Generation (GWh) In Ascending---

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
7,Florida,15,535,12.3,453,South
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
1,Arizona,48,1078,22.5,2550,West
0,California,289,4395,15.3,10826,West

In [14]:
print('---By Installed Capacity (MW) In Deascending---')
df.sort_values(by='Installed Capacity (MW)' , ascending = False)

---By Installed Capacity (MW) In Deascending---

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South
4,Connecticut,20,118,5.9,235,East
6,New York,13,53,4.1,84,East

e. List top 5 plants for their Generation

In [15]:
print('----- Top 5 In Generation -----')
df.sort_values(by='Generation (GWh)' , ascending = False).head(5)

----- Top 5 In Generation -----

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
7,Florida,15,535,12.3,453,South

f. Display all plant details for states – California, Nevada, Arizona and Texas

In [16]:
df[df['State'].isin(['California','Nevada','Arizona','Texas'])]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South

 g. Group the plants by region, find – min/max capacity plant for each group

In [17]:
df.groupby('Region')['Installed Capacity (MW)'].agg(Min_Capacity = min , Max_Capacity = max).reset_index()

  Region  Min_Capacity  Max_Capacity
0   East            53           118
1  North           261           261
2  South           187           535
3   West           238          4395

 h. Add following information to the existing details for the plants North Carolina 148 669 4.5 1162 North

In [18]:
new_data = {'State':'North Carolina',
            'Number of Solar Plants' :148,
            'Installed Capacity (MW)' :669,
            'Average MW Per Plant' :4.5,
            'Generation (GWh)' :1162,
            'Region' : 'North'
           }
df = pd.concat([df,pd.DataFrame([new_data])],ignore_index = True)
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,North Carolina,148,669,4.5,1162,North

------ Q3 ------

Read csv gapminder2007.csv
a.	Display data for all Asian countries
b.	Display top and bottom 15 rows
c.	Show all the rows where life expectancy is more than 50 years and less than 80 years
d.	Show data for India, America and France
e.	Show data for all countries where name starts with ‘A’
f.	Show min/max and mean GDP and Population for each continent
g.	Show population and life expectancy for all countries 
h.	Sort the data by country names (ascending) and GDP (descending)
i.	Find top 20 most populous countries
j.	Delete all rows for a specific country
k.	Change all column names to title case
l.	Change column names: pop to Population, gdpPercap to GDP_Percap
m.	Increase Life Expectancy by 2 years for all African countries
n.	Find all the rows that contain NA values
o.	Fill NA values with 0 for numeric columns

In [19]:
df = pd.read_csv('gapminder2007.csv')
df

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

a.	Display data for all Asian countries

In [20]:
df[df['continent'] == 'Asia']

                country         pop continent  lifeExp     gdpPercap
0           Afghanistan    31889923      Asia   43.828    974.580338
7               Bahrain      708573      Asia   75.635  29796.048340
8            Bangladesh   150448339      Asia   64.062   1391.253792
18             Cambodia    14131858      Asia   59.723   1713.778686
24                China  1318683096      Asia   72.961   4959.114854
55     Hong Kong, China     6980412      Asia   82.208  39724.978670
58                India  1110396331      Asia   64.698   2452.210407
59            Indonesia   223547000      Asia   70.650   3540.651564
60                 Iran    69453570      Asia   70.964  11605.714490
61                 Iraq    27499638      Asia   59.545   4471.061906
63               Israel     6426679      Asia   80.745  25523.277100
66                Japan   127467972      Asia   82.603  31656.068060
67               Jordan     6053193      Asia   72.535   4519.461171
69     Korea, Dem. Rep.    23301725      Asia   67.297   1593.065480
70          Korea, Rep.    49044790      Asia   78.623  23348.139730
71               Kuwait     2505559      Asia   77.588  47306.989780
72              Lebanon     3921278      Asia   71.993  10461.058680
78             Malaysia    24821286      Asia   74.241  12451.655800
83             Mongolia     2874127      Asia   66.803   3095.772271
87              Myanmar    47761980      Asia   62.069    944.000000
89                Nepal    28901790      Asia   63.785   1091.359778
96                 Oman     3204897      Asia   75.640  22316.192870
97             Pakistan   169270617      Asia   65.483   2605.947580
101         Philippines    91077287      Asia   71.688   3190.481016
109        Saudi Arabia    27601038      Asia   72.777  21654.831940
113           Singapore     4553009      Asia   79.972  47143.179640
119           Sri Lanka    20378239      Asia   72.396   3970.095407
124               Syria    19314747      Asia   74.143   4184.548089
125              Taiwan    23174294      Asia   78.400  28718.276840
127            Thailand    65068149      Asia   70.616   7458.396327
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906

b.	Display top and bottom 15 rows

In [21]:
print('------ Top 15 ------')
df.head(15)

------ Top 15 ------

                   country        pop continent  lifeExp     gdpPercap
0              Afghanistan   31889923      Asia   43.828    974.580338
1                  Albania    3600523    Europe   76.423   5937.029526
2                  Algeria   33333216    Africa   72.301   6223.367465
3                   Angola   12420476    Africa   42.731   4797.231267
4                Argentina   40301927  Americas   75.320  12779.379640
5                Australia   20434176   Oceania   81.235  34435.367440
6                  Austria    8199783    Europe   79.829  36126.492700
7                  Bahrain     708573      Asia   75.635  29796.048340
8               Bangladesh  150448339      Asia   64.062   1391.253792
9                  Belgium   10392226    Europe   79.441  33692.605080
10                   Benin    8078314    Africa   56.728   1441.284873
11                 Bolivia    9119152  Americas   65.554   3822.137084
12  Bosnia and Herzegovina    4552198    Europe   74.852   7446.298803
13                Botswana    1639131    Africa   50.728  12569.851770
14                  Brazil  190010647  Americas   72.390   9065.800825

In [22]:
print('------ Bottom 15 ------')
df.tail(15)

------ Bottom 15 ------

                 country        pop continent  lifeExp     gdpPercap
127             Thailand   65068149      Asia   70.616   7458.396327
128                 Togo    5701579    Africa   58.420    882.969944
129  Trinidad and Tobago    1056608  Americas   69.819  18008.509240
130              Tunisia   10276158    Africa   73.923   7092.923025
131               Turkey   71158647    Europe   71.777   8458.276384
132               Uganda   29170398    Africa   51.542   1056.380121
133       United Kingdom   60776238    Europe   79.425  33203.261280
134        United States  301139947  Americas   78.242  42951.653090
135              Uruguay    3447496  Americas   76.384  10611.462990
136            Venezuela   26084662  Americas   73.747  11415.805690
137              Vietnam   85262356      Asia   74.249   2441.576404
138   West Bank and Gaza    4018332      Asia   73.422   3025.349798
139          Yemen, Rep.   22211743      Asia   62.698   2280.769906
140               Zambia   11746035    Africa   42.384   1271.211593
141             Zimbabwe   12311143    Africa   43.487    469.709298

c.	Show all the rows where life expectancy is more than 50 years and less than 80 years

In [23]:
df[(df['lifeExp'] > 50) & (df['lifeExp'] < 80)]

                country       pop continent  lifeExp     gdpPercap
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
4             Argentina  40301927  Americas   75.320  12779.379640
6               Austria   8199783    Europe   79.829  36126.492700
7               Bahrain    708573      Asia   75.635  29796.048340
..                  ...       ...       ...      ...           ...
135             Uruguay   3447496  Americas   76.384  10611.462990
136           Venezuela  26084662  Americas   73.747  11415.805690
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906

[110 rows x 5 columns]

d.	Show data for India, America and France

In [24]:
df[df['country'].isin(['India','America','France'])]

   country         pop continent  lifeExp     gdpPercap
44  France    61083916    Europe   80.657  30470.016700
58   India  1110396331      Asia   64.698   2452.210407

e.	Show data for all countries where name starts with ‘A’

In [25]:
filt = list(map(lambda x : x.startswith('A'),df['country']))
df[filt]

       country       pop continent  lifeExp     gdpPercap
0  Afghanistan  31889923      Asia   43.828    974.580338
1      Albania   3600523    Europe   76.423   5937.029526
2      Algeria  33333216    Africa   72.301   6223.367465
3       Angola  12420476    Africa   42.731   4797.231267
4    Argentina  40301927  Americas   75.320  12779.379640
5    Australia  20434176   Oceania   81.235  34435.367440
6      Austria   8199783    Europe   79.829  36126.492700

f.	Show min/max and mean GDP and Population for each continent

In [26]:
df.groupby('continent').agg(Min_GDP =('gdpPercap','min'), Max_GDP = ('gdpPercap','max'), Mean_GDP = ('gdpPercap','mean'),Min_Pop =('pop','min'), Max_Pop = ('pop','max'), Mean_Pop = ('pop','mean')).reset_index()

,continent,Min_GDP,Max_GDP,Mean_GDP,Min_Pop,Max_Pop,Mean_Pop
0,Africa,277.551859,13206.48452,3089.032605,199579,135031164,1.787576e+07
1,Americas,1201.637154,42951.65309,11003.031625,1056608,301139947,3.595485e+07
2,Asia,944.000000,47306.98978,12473.026870,708573,1318683096,1.155138e+08
3,Europe,5937.029526,49357.19017,25054.481636,301931,82400996,1.953662e+07
4,Oceania,25185.009110,34435.36744,29810.188275,4115771,20434176,1.227497e+07

g.	Show population and life expectancy for all countries

In [27]:
df[['country','pop','lifeExp']]

                country       pop  lifeExp
0           Afghanistan  31889923   43.828
1               Albania   3600523   76.423
2               Algeria  33333216   72.301
3                Angola  12420476   42.731
4             Argentina  40301927   75.320
..                  ...       ...      ...
137             Vietnam  85262356   74.249
138  West Bank and Gaza   4018332   73.422
139         Yemen, Rep.  22211743   62.698
140              Zambia  11746035   42.384
141            Zimbabwe  12311143   43.487

[142 rows x 3 columns]

h.	Sort the data by country names (ascending) and GDP (descending)

In [28]:
print('----- Sort By Country Name -----')
df.sort_values(by = 'country' ,ascending = True)

----- Sort By Country Name -----

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [29]:
print('----- Sort By GDP Name -----')
df.sort_values(by = 'gdpPercap' ,ascending = False)

----- Sort By GDP Name -----

              country        pop continent  lifeExp     gdpPercap
95             Norway    4627926    Europe   80.196  49357.190170
71             Kuwait    2505559      Asia   77.588  47306.989780
113         Singapore    4553009      Asia   79.972  47143.179640
134     United States  301139947  Americas   78.242  42951.653090
62            Ireland    4109086    Europe   78.885  40675.996350
..                ...        ...       ...      ...           ...
52      Guinea-Bissau    1472041    Africa   46.388    579.231743
141          Zimbabwe   12311143    Africa   43.487    469.709298
17            Burundi    8390505    Africa   49.580    430.070692
74            Liberia    3193942    Africa   45.678    414.507341
27   Congo, Dem. Rep.   64606759    Africa   46.462    277.551859

[142 rows x 5 columns]

i.	Find top 20 most populous countries

In [30]:
print('----- Top 20 Most Populous Countries -----')
df.sort_values(by = 'pop',ascending = False).head(20)

----- Top 20 Most Populous Countries -----

              country         pop continent  lifeExp     gdpPercap
24              China  1318683096      Asia   72.961   4959.114854
58              India  1110396331      Asia   64.698   2452.210407
134     United States   301139947  Americas   78.242  42951.653090
59          Indonesia   223547000      Asia   70.650   3540.651564
14             Brazil   190010647  Americas   72.390   9065.800825
97           Pakistan   169270617      Asia   65.483   2605.947580
8          Bangladesh   150448339      Asia   64.062   1391.253792
94            Nigeria   135031164    Africa   46.859   2013.977305
66              Japan   127467972      Asia   82.603  31656.068060
82             Mexico   108700891  Americas   76.195  11977.574960
101       Philippines    91077287      Asia   71.688   3190.481016
137           Vietnam    85262356      Asia   74.249   2441.576404
47            Germany    82400996    Europe   79.406  32170.374420
38              Egypt    80264543    Africa   71.338   5581.180998
42           Ethiopia    76511887    Africa   52.947    690.805576
131            Turkey    71158647    Europe   71.777   8458.276384
60               Iran    69453570      Asia   70.964  11605.714490
127          Thailand    65068149      Asia   70.616   7458.396327
27   Congo, Dem. Rep.    64606759    Africa   46.462    277.551859
44             France    61083916    Europe   80.657  30470.016700

j.	Delete all rows for a specific country

In [31]:
df.drop(df[(df['country'] == 'India')].index,inplace = True)
df

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[141 rows x 5 columns]

In [33]:
df[df['country'] == 'India']

Empty DataFrame
Columns: [country, pop, continent, lifeExp, gdpPercap]
Index: []

k.	Change all column names to title case

In [34]:
df.columns = list(map(lambda x : x.title(),df.columns))
df

                Country       Pop Continent  Lifeexp     Gdppercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[141 rows x 5 columns]

l.	Change column names: pop to Population, gdpPercap to GDP_Percap

In [35]:
df.rename (columns = {'Pop':'Population','Gdppercap':'GDP_Percap'},inplace = True)
df

                Country  Population Continent  Lifeexp    GDP_Percap
0           Afghanistan    31889923      Asia   43.828    974.580338
1               Albania     3600523    Europe   76.423   5937.029526
2               Algeria    33333216    Africa   72.301   6223.367465
3                Angola    12420476    Africa   42.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   42.384   1271.211593
141            Zimbabwe    12311143    Africa   43.487    469.709298

[141 rows x 5 columns]

m.	Increase Life Expectancy by 2 years for all African countries

In [36]:
df['Lifeexp'] = [x+2 for x in df['Lifeexp']]
df

                Country  Population Continent  Lifeexp    GDP_Percap
0           Afghanistan    31889923      Asia   45.828    974.580338
1               Albania     3600523    Europe   78.423   5937.029526
2               Algeria    33333216    Africa   74.301   6223.367465
3                Angola    12420476    Africa   44.731   4797.231267
4             Argentina    40301927  Americas   77.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   76.249   2441.576404
138  West Bank and Gaza     4018332      Asia   75.422   3025.349798
139         Yemen, Rep.    22211743      Asia   64.698   2280.769906
140              Zambia    11746035    Africa   44.384   1271.211593
141            Zimbabwe    12311143    Africa   45.487    469.709298

[141 rows x 5 columns]

n.	Find all the rows that contain NA values

In [38]:
df.isnull().sum()

Country       0
Population    0
Continent     0
Lifeexp       0
GDP_Percap    0
dtype: int64

o.	Fill NA values with 0 for numeric columns

In [39]:
print('There is No NA Values in DataFrame')

There is No NA Values in DataFrame