In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({'First':['Viraj','Ram','Harsh','Priyanshu',np.nan,'Avani',None],
                  'Last':['P','N','Missing','NA','Missing',None,np.nan],
                   'Email' : ['viraj@gmail.com','ram@gmail.com','sai@gmail.com',np.nan,None,'Avani@gmail.com',np.nan],
                  'Age' : [23,43,13,None,15,None,40]
                  })
df

       First     Last            Email   Age
0      Viraj        P  viraj@gmail.com  23.0
1        Ram        N    ram@gmail.com  43.0
2      Harsh  Missing    sai@gmail.com  13.0
3  Priyanshu       NA              NaN   NaN
4        NaN  Missing              NaN  15.0
5      Avani      NaN  Avani@gmail.com   NaN
6        NaN      NaN              NaN  40.0

In [5]:
df.isnull()

   First   Last  Email    Age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True   True
4   True  False   True  False
5  False   True  False   True
6   True   True   True  False

In [6]:
df.isnull().sum()

First    2
Last     2
Email    3
Age      2
dtype: int64

In [7]:
df.isna()

   First   Last  Email    Age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True   True
4   True  False   True  False
5  False   True  False   True
6   True   True   True  False

In [8]:
df.isna().sum()

First    2
Last     2
Email    3
Age      2
dtype: int64

In [9]:
df.dropna()

   First     Last            Email   Age
0  Viraj        P  viraj@gmail.com  23.0
1    Ram        N    ram@gmail.com  43.0
2  Harsh  Missing    sai@gmail.com  13.0

In [10]:
df.dropna(how = 'all')

       First     Last            Email   Age
0      Viraj        P  viraj@gmail.com  23.0
1        Ram        N    ram@gmail.com  43.0
2      Harsh  Missing    sai@gmail.com  13.0
3  Priyanshu       NA              NaN   NaN
4        NaN  Missing              NaN  15.0
5      Avani      NaN  Avani@gmail.com   NaN
6        NaN      NaN              NaN  40.0

In [12]:
df.dropna(subset = ['Age'])

   First     Last            Email   Age
0  Viraj        P  viraj@gmail.com  23.0
1    Ram        N    ram@gmail.com  43.0
2  Harsh  Missing    sai@gmail.com  13.0
4    NaN  Missing              NaN  15.0
6    NaN      NaN              NaN  40.0

In [13]:
df.dropna(subset = ['Email'])

   First     Last            Email   Age
0  Viraj        P  viraj@gmail.com  23.0
1    Ram        N    ram@gmail.com  43.0
2  Harsh  Missing    sai@gmail.com  13.0
5  Avani      NaN  Avani@gmail.com   NaN

In [14]:
df.fillna(0)

       First     Last            Email   Age
0      Viraj        P  viraj@gmail.com  23.0
1        Ram        N    ram@gmail.com  43.0
2      Harsh  Missing    sai@gmail.com  13.0
3  Priyanshu       NA                0   0.0
4          0  Missing                0  15.0
5      Avani        0  Avani@gmail.com   0.0
6          0        0                0  40.0

In [15]:
df.fillna({'Email':'test@gmail.com','Age':0})

       First     Last            Email   Age
0      Viraj        P  viraj@gmail.com  23.0
1        Ram        N    ram@gmail.com  43.0
2      Harsh  Missing    sai@gmail.com  13.0
3  Priyanshu       NA   test@gmail.com   0.0
4        NaN  Missing   test@gmail.com  15.0
5      Avani      NaN  Avani@gmail.com   0.0
6        NaN      NaN   test@gmail.com  40.0

In [21]:
df.fillna({'Fisrt' : 0,'Email':'test@gmail.com'})

       First     Last            Email   Age
0      Viraj        P  viraj@gmail.com  23.0
1        Ram        N    ram@gmail.com  43.0
2      Harsh  Missing    sai@gmail.com  13.0
3  Priyanshu       NA   test@gmail.com   NaN
4        NaN  Missing   test@gmail.com  15.0
5      Avani      NaN  Avani@gmail.com   NaN
6        NaN      NaN   test@gmail.com  40.0

In [17]:
df.isna().all()

First    False
Last     False
Email    False
Age      False
dtype: bool

In [18]:
df.isna().any()

First    True
Last     True
Email    True
Age      True
dtype: bool