In [36]:
import pandas as pd
import numpy as np

In [37]:
arr = np.array([10,20,30,40,50])
series = pd.Series(arr)
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [38]:
names = ["Akshay", "Amol", "Aryan", "Ayush"]
series = pd.Series(names)
series

0    Akshay
1      Amol
2     Aryan
3     Ayush
dtype: str

In [39]:
head = pd.Series({'USA':'NYC','India':'Pune','UK':'London','France':'Paris'})
head

USA          NYC
India       Pune
UK        London
France     Paris
dtype: str

In [40]:
head.index

Index(['USA', 'India', 'UK', 'France'], dtype='str')

In [41]:
head.values

<StringArray>
['NYC', 'Pune', 'London', 'Paris']
Length: 4, dtype: str

In [42]:
head.loc['India']

'Pune'

In [43]:
head.iloc[2]

'London'

In [44]:
series.loc[1]

'Amol'

In [45]:
head['India':'France']

India       Pune
UK        London
France     Paris
dtype: str

In [46]:
head[1:3]

India      Pune
UK       London
dtype: str

In [47]:
count = pd.Series({'USA':30,'India':500,'UK':50,'France':109})
count

USA        30
India     500
UK         50
France    109
dtype: int64

In [48]:
df = pd.DataFrame({'Head Office' : head, 'Count' : count})
df

       Head Office  Count
USA            NYC     30
India         Pune    500
UK          London     50
France       Paris    109

In [49]:
df = pd.DataFrame({'Name' :['Akshay','Amol','Aryan','Ayush'],
                  'Age' : [33,28,40,39],
                   'City' : ['Pune','Mumbai','Delhi','Vadodara']
                  })
df

     Name  Age      City
0  Akshay   33      Pune
1    Amol   28    Mumbai
2   Aryan   40     Delhi
3   Ayush   39  Vadodara

In [50]:
df = pd.DataFrame(data = [[500,15,40],[400,12,30],[250,13,15],[300,14,15]],
                          index = ['Tata','Maruti','Hyundai','Honda'],
                            columns = ['Total Sale', 'Profit %', 'Market Share'])
df

         Total Sale  Profit %  Market Share
Tata            500        15            40
Maruti          400        12            30
Hyundai         250        13            15
Honda           300        14            15

In [51]:
df.loc['Tata']

Total Sale      500
Profit %         15
Market Share     40
Name: Tata, dtype: int64

In [52]:
df.iloc[3]

Total Sale      300
Profit %         14
Market Share     15
Name: Honda, dtype: int64

In [53]:
df.iloc[-2]

Total Sale      250
Profit %         13
Market Share     15
Name: Hyundai, dtype: int64

In [54]:
df['Tata':'Hyundai']

         Total Sale  Profit %  Market Share
Tata            500        15            40
Maruti          400        12            30
Hyundai         250        13            15

In [55]:
df.loc['Tata':'Hyundai','Profit %']

Tata       15
Maruti     12
Hyundai    13
Name: Profit %, dtype: int64

In [59]:
df.loc['Tata':'Hyundai',['Profit %','Total Sale']]

         Profit %  Total Sale
Tata           15         500
Maruti         12         400
Hyundai        13         250

In [60]:
df.loc['Tata':'Hyundai','Profit %']

Tata       15
Maruti     12
Hyundai    13
Name: Profit %, dtype: int64

In [64]:
df.loc['Tata':'Hyundai','Profit %' :'Total Sale']

Empty DataFrame
Columns: []
Index: [Tata, Maruti, Hyundai]

In [65]:
df.iloc[1:3,1:2]

         Profit %
Maruti         12
Hyundai        13

In [66]:
df.iloc[1:3,2]

Maruti     30
Hyundai    15
Name: Market Share, dtype: int64