In [1]:
import pandas as pd

In [22]:
df = pd.DataFrame({'FullName' : ['Ramehswar ','Hitesh','Priyanshu','Om','Mukkisa Sai Harshith Reddy','Om'],
                    'Email' : ['Ram1234@gmail.com','heet65@gmail.com','priya232@gmail.com','om21@gmail.com','harsh909@gmail.com','omkar123@gmail.com'],
                   'Salary' : [10000,15000,23000,9000,54000,6000]
                  })
df

                     FullName               Email  Salary
0                  Ramehswar    Ram1234@gmail.com   10000
1                      Hitesh    heet65@gmail.com   15000
2                   Priyanshu  priya232@gmail.com   23000
3                          Om      om21@gmail.com    9000
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000
5                          Om  omkar123@gmail.com    6000

In [23]:
df.sort_values(by = 'FullName')

                     FullName               Email  Salary
1                      Hitesh    heet65@gmail.com   15000
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000
3                          Om      om21@gmail.com    9000
5                          Om  omkar123@gmail.com    6000
2                   Priyanshu  priya232@gmail.com   23000
0                  Ramehswar    Ram1234@gmail.com   10000

In [24]:
df.sort_values(by = 'Salary')

                     FullName               Email  Salary
5                          Om  omkar123@gmail.com    6000
3                          Om      om21@gmail.com    9000
0                  Ramehswar    Ram1234@gmail.com   10000
1                      Hitesh    heet65@gmail.com   15000
2                   Priyanshu  priya232@gmail.com   23000
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000

In [25]:
df.sort_values(by = ['FullName','Salary'])

                     FullName               Email  Salary
1                      Hitesh    heet65@gmail.com   15000
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000
5                          Om  omkar123@gmail.com    6000
3                          Om      om21@gmail.com    9000
2                   Priyanshu  priya232@gmail.com   23000
0                  Ramehswar    Ram1234@gmail.com   10000

In [34]:
df.sort_values(by = 'Salary',ascending = False)

                     FullName               Email  Salary
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000
2                   Priyanshu  priya232@gmail.com   23000
1                      Hitesh    heet65@gmail.com   15000
0                  Ramehswar    Ram1234@gmail.com   10000
3                          Om      om21@gmail.com    9000
5                          Om  omkar123@gmail.com    6000

In [32]:
df.sort_index(ascending = False)

                     FullName               Email  Salary
5                          Om  omkar123@gmail.com    6000
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000
3                          Om      om21@gmail.com    9000
2                   Priyanshu  priya232@gmail.com   23000
1                      Hitesh    heet65@gmail.com   15000
0                  Ramehswar    Ram1234@gmail.com   10000