In [63]:
import pandas as pd

In [64]:
df = pd.DataFrame({'FullName' : ['Ramehswar ','Hitesh','Priya','Om','Mukkisa Sai Harshith Reddy','Om'],
                    'Email' : ['Ram1234@gmail.com','heet65@gmail.com','priya232@gmail.com','om21@gmail.com','harsh909@gmail.com','omkar123@gmail.com'],
                   'Salary' : [10000,15000,23000,9000,54000,6000]
                  })

In [65]:
df['Bonus'] = df['Salary'] * 0.2
df

                     FullName               Email  Salary    Bonus
0                  Ramehswar    Ram1234@gmail.com   10000   2000.0
1                      Hitesh    heet65@gmail.com   15000   3000.0
2                       Priya  priya232@gmail.com   23000   4600.0
3                          Om      om21@gmail.com    9000   1800.0
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000  10800.0
5                          Om  omkar123@gmail.com    6000   1200.0

In [66]:
df['Gender'] = ['M','M','F','M','M','F']
df

                     FullName               Email  Salary    Bonus Gender
0                  Ramehswar    Ram1234@gmail.com   10000   2000.0      M
1                      Hitesh    heet65@gmail.com   15000   3000.0      M
2                       Priya  priya232@gmail.com   23000   4600.0      F
3                          Om      om21@gmail.com    9000   1800.0      M
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000  10800.0      M
5                          Om  omkar123@gmail.com    6000   1200.0      F

In [67]:
df['Gender'] = df['Gender'].map({'F' : 'Female','M':'Male'})
df

                     FullName               Email  Salary    Bonus  Gender
0                  Ramehswar    Ram1234@gmail.com   10000   2000.0    Male
1                      Hitesh    heet65@gmail.com   15000   3000.0    Male
2                       Priya  priya232@gmail.com   23000   4600.0  Female
3                          Om      om21@gmail.com    9000   1800.0    Male
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000  10800.0    Male
5                          Om  omkar123@gmail.com    6000   1200.0  Female

In [68]:
df.columns = [s.lower() for s in df.columns]
df

                     fullname               email  salary    bonus  gender
0                  Ramehswar    Ram1234@gmail.com   10000   2000.0    Male
1                      Hitesh    heet65@gmail.com   15000   3000.0    Male
2                       Priya  priya232@gmail.com   23000   4600.0  Female
3                          Om      om21@gmail.com    9000   1800.0    Male
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000  10800.0    Male
5                          Om  omkar123@gmail.com    6000   1200.0  Female

In [69]:
df.columns = list(map(lambda x : x.title(),df.columns))
df

                     Fullname               Email  Salary    Bonus  Gender
0                  Ramehswar    Ram1234@gmail.com   10000   2000.0    Male
1                      Hitesh    heet65@gmail.com   15000   3000.0    Male
2                       Priya  priya232@gmail.com   23000   4600.0  Female
3                          Om      om21@gmail.com    9000   1800.0    Male
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000  10800.0    Male
5                          Om  omkar123@gmail.com    6000   1200.0  Female

In [70]:
df.rename(columns = {'Email' : 'Email Id'},inplace  = True)
df

                     Fullname            Email Id  Salary    Bonus  Gender
0                  Ramehswar    Ram1234@gmail.com   10000   2000.0    Male
1                      Hitesh    heet65@gmail.com   15000   3000.0    Male
2                       Priya  priya232@gmail.com   23000   4600.0  Female
3                          Om      om21@gmail.com    9000   1800.0    Male
4  Mukkisa Sai Harshith Reddy  harsh909@gmail.com   54000  10800.0    Male
5                          Om  omkar123@gmail.com    6000   1200.0  Female

In [71]:
df.loc[2,'Email Id'] = 'changepriyu@gmail.com'
df.loc[0,'Email Id'] = 'ram@gmail.com'
df

                     Fullname               Email Id  Salary    Bonus  Gender
0                  Ramehswar           ram@gmail.com   10000   2000.0    Male
1                      Hitesh       heet65@gmail.com   15000   3000.0    Male
2                       Priya  changepriyu@gmail.com   23000   4600.0  Female
3                          Om         om21@gmail.com    9000   1800.0    Male
4  Mukkisa Sai Harshith Reddy     harsh909@gmail.com   54000  10800.0    Male
5                          Om     omkar123@gmail.com    6000   1200.0  Female

In [72]:
df.apply(len)

Fullname    6
Email Id    6
Salary      6
Bonus       6
Gender      6
dtype: int64

In [73]:
df.apply(min)

Fullname                   Hitesh
Email Id    changepriyu@gmail.com
Salary                       6000
Bonus                      1200.0
Gender                     Female
dtype: object

In [74]:
df['Diff'] = df.apply(lambda row : row['Salary'] - row['Bonus'],axis=1)
df

,Fullname,Email Id,Salary,Bonus,Gender,Diff
0,Ramehswar,ram@gmail.com,10000,2000.0,Male,8000.0
1,Hitesh,heet65@gmail.com,15000,3000.0,Male,12000.0
2,Priya,changepriyu@gmail.com,23000,4600.0,Female,18400.0
3,Om,om21@gmail.com,9000,1800.0,Male,7200.0
4,Mukkisa Sai Harshith Reddy,harsh909@gmail.com,54000,10800.0,Male,43200.0
5,Om,omkar123@gmail.com,6000,1200.0,Female,4800.0

In [75]:
df = df.replace({'Om':'Omkar'})
df

,Fullname,Email Id,Salary,Bonus,Gender,Diff
0,Ramehswar,ram@gmail.com,10000,2000.0,Male,8000.0
1,Hitesh,heet65@gmail.com,15000,3000.0,Male,12000.0
2,Priya,changepriyu@gmail.com,23000,4600.0,Female,18400.0
3,Omkar,om21@gmail.com,9000,1800.0,Male,7200.0
4,Mukkisa Sai Harshith Reddy,harsh909@gmail.com,54000,10800.0,Male,43200.0
5,Omkar,omkar123@gmail.com,6000,1200.0,Female,4800.0

In [58]:
df['Fullname'] = df['Fullname'] . map({'Omkar':'Om'})
df

  Fullname               Email Id  Salary    Bonus  Gender     Diff
0      NaN          ram@gmail.com   10000   2000.0    Male   8000.0
1      NaN       heet65@gmail.com   15000   3000.0    Male  12000.0
2      NaN  changepriyu@gmail.com   23000   4600.0  Female  18400.0
3    Omkar         om21@gmail.com    9000   1800.0    Male   7200.0
4      NaN     harsh909@gmail.com   54000  10800.0    Male  43200.0
5    Omkar     omkar123@gmail.com    6000   1200.0  Female   4800.0

  Fullname               Email Id  Salary    Bonus  Gender     Diff
0      NaN          ram@gmail.com   10000   2000.0    Male   8000.0
1      NaN       heet65@gmail.com   15000   3000.0    Male  12000.0
2      NaN  changepriyu@gmail.com   23000   4600.0  Female  18400.0
3    Omkar         om21@gmail.com    9000   1800.0    Male   7200.0
4      NaN     harsh909@gmail.com   54000  10800.0    Male  43200.0
5    Omkar     omkar123@gmail.com    6000   1200.0  Female   4800.0